import "@styles/globals.scss";

import CustomAuthProvider from '@providers/CustomAuthProvider';
import ErrorBoundaryProvider from '@providers/ErrorBoundaryProvider';
import ReactQueryProvider from '@providers/ReactQueryProvider';
import ReactToastifyProvider from '@providers/ReactToastifyProvider';
import ReactPublicContextProvider from '@providers/ReactPublicContextProvider';
import ReactLoadingProvider from '@providers/ReactLoadingProvider';


// Font files can be colocated inside of `pages`
export const metadata = {
  title: "Bookagri",
  description: "Generated by Bookagri",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        {/* {pageProps?.seo ? <SEOWrapper {...pageProps.seo} /> : null} */}
        <CustomAuthProvider>
          <ErrorBoundaryProvider>
            <ReactQueryProvider>
              <ReactToastifyProvider>
                <ReactPublicContextProvider>
                  <ReactLoadingProvider>
                    {children}
                  </ReactLoadingProvider>
                </ReactPublicContextProvider>
              </ReactToastifyProvider>
            </ReactQueryProvider>
          </ErrorBoundaryProvider>
        </CustomAuthProvider>
      </body>
    </html>
  );
}
