import localFont from 'next/font/local'
import "@styles/globals.scss";
 
// Font files can be colocated inside of `pages`
const Gellix = localFont({ src: '../utils/font/gellix-11.ttf' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Gellix.className}>{children}</body>
    </html>
  );
}
