import '@styles/globals.scss';

import CustomAuthProvider from '@providers/CustomAuthProvider';
import ErrorBoundaryProvider from '@providers/ErrorBoundaryProvider';
import ReactQueryProvider from '@providers/ReactQueryProvider';
import ReactToastifyProvider from '@providers/ReactToastifyProvider';
import ReactPublicContextProvider from '@providers/ReactPublicContextProvider';
import ReactLoadingProvider from '@providers/ReactLoadingProvider';

export const metadata = {
  title: 'Bookagri',
  description: 'Generated by Bookagri',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body>
        <CustomAuthProvider>
          <ErrorBoundaryProvider>
            <ReactQueryProvider>
              <ReactToastifyProvider>
                <ReactPublicContextProvider>
                  <ReactLoadingProvider>{children}</ReactLoadingProvider>
                </ReactPublicContextProvider>
              </ReactToastifyProvider>
            </ReactQueryProvider>
          </ErrorBoundaryProvider>
        </CustomAuthProvider>
      </body>
    </html>
  );
}
