name: QA Frontend Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the selected branch
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Cache dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install dependencies (ignore peer conflicts)
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 5️⃣ Set placeholder API URL for frontend
      - name: Set frontend environment
        run: |
          echo "REACT_APP_API_URL=${{ secrets.QA_BACKEND_URL }}" > .env.production
          cat .env.production

      # 6️⃣ Build frontend
      - name: Build frontend
        run: npm run build

      # 7️⃣ Optional: upload artifacts (if you want to save build output)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: .next/
