name: QA Frontend Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout the branch
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Cache npm dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 5️⃣ Set placeholder API URL
      - name: Set frontend environment
        run: |
          echo "REACT_APP_API_URL=${{ secrets.QA_BACKEND_URL }}" > .env.production
          cat .env.production

      # 6️⃣ Build frontend
      - name: Build frontend
        run: npm run build

      # 7️⃣ Trigger Amplify Console redeploy
      - name: Trigger Amplify redeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          echo "Triggering Amplify redeploy for branch: $BRANCH"
          aws amplify start-job \
            --app-id $AMPLIFY_APP_ID \
            --branch-name $BRANCH \
            --job-type RELEASE \
            --region $AWS_REGION

      # 8️⃣ Output redeploy info
      - name: Deployed info
        run: |
          echo "✅ QA redeploy triggered for branch: ${{ github.event.inputs.branch }}"
          echo "Check Amplify Console to see deployment progress."
