name: QA Manual Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the selected branch
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Cache npm dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install dependencies (ignore peer conflicts)
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 5️⃣ Set placeholder API URL for frontend
      - name: Set frontend environment
        run: |
          echo "REACT_APP_API_URL=${{ secrets.QA_BACKEND_URL }}" > .env.production
          cat .env.production

      # 6️⃣ Build frontend
      - name: Build frontend
        run: npm run build

      # 7️⃣ Deploy frontend to Amplify Hosting
      - name: Deploy frontend to Amplify
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Publishing frontend for branch: ${{ github.event.inputs.branch }}"
          amplify publish --yes

      # 8️⃣ Show deployed URL
      - name: Show deployed URL
        run: |
          echo "✅ QA environment deployed at: https://${{ github.event.inputs.branch }}.<your-amplify-app>.amplifyapp.com"
