name: QA Manual Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the selected branch
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 3️⃣ Build frontend
      - name: Build frontend
        run: npm run build

      # 4️⃣ Setup Amplify CLI
      - name: Setup Amplify CLI
        run: npm install -g @aws-amplify/cli

      # 5️⃣ Deploy to Amplify using branch name as environment / subdomain
      - name: Deploy to Amplify
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          QA_BACKEND_URL: ${{ secrets.QA_BACKEND_URL }}
        run: |
          BRANCH="${{ github.event.inputs.branch }}"
          echo "Deploying branch: $BRANCH"

          # Pull existing environment if it exists
          amplify pull --appId $AMPLIFY_APP_ID --envName $BRANCH || echo "Env does not exist yet"

          # Checkout or create environment
          amplify env checkout $BRANCH || amplify env add --name $BRANCH --appId $AMPLIFY_APP_ID --yes

          # Set backend URL for this environment
          echo "REACT_APP_API_URL=$QA_BACKEND_URL" > .env.production

          # Push and publish
          amplify push --yes
          amplify publish --yes

      # 6️⃣ Show deployed URL
      - name: Show deployed URL
        run: |
          echo "✅ QA environment deployed at: https://${{ github.event.inputs.branch }}.<your-amplify-app>.amplifyapp.com"
